/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UserController;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.User;

/**
 *
 * @author Valdez
 */
public class ChangePasswordView extends javax.swing.JFrame {

    private UserController userController = new UserController(this);
    private ClientMainView clientMainView;
    private User user;

    /**
     * Creates new form ChangePasswordView
     */
    public ChangePasswordView(User user, ClientMainView clientMainView) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
        }
        this.user = user;
        this.clientMainView = clientMainView;
        initComponents();
        this.setTitle("Change password");
    }

    private String SHA_1(String input) {
        try {
            MessageDigest mDigest = MessageDigest.getInstance("SHA1");
            byte[] result = mDigest.digest(input.getBytes());
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < result.length; i++) {
                sb.append(Integer.toString((result[i] & 0xff) + 0x100, 16).substring(1));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException ex) {
            showMessage(ex.getStackTrace().toString());
        }
        return null;
    }

    public void returnNewPassword(User user) {
        this.user = user;
        clientMainView.setUser(user);
        this.dispose();
        clientMainView.showMessage("your password has been updated.");
    }

    public User getUserNewPassword() {
        User model = new User();
        model.setId(user.getId());
        model.setOldPassword(SHA_1(new String(pwd_OldPassword.getPassword())));
        model.setPassword_hash(SHA_1(new String(pwd_NewPassword.getPassword())));
        pwd_OldPassword.setText("");
        pwd_NewPassword.setText("");
        pwd_ConfirmNewPassword.setText("");
        pwd_OldPassword.requestFocusInWindow();
        return model;
    }

    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_Form = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics grphcs) {
                super.paintComponent(grphcs);
                Graphics2D g2d = (Graphics2D) grphcs;
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                Color color = new Color(120, 36, 111);
                GradientPaint gp = new GradientPaint(0, 0, color.brighter(), 0, getHeight(), color.darker());
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        lbl_ForOldPassword = new javax.swing.JLabel();
        pwd_OldPassword = new javax.swing.JPasswordField();
        lbl_ForNewPassword = new javax.swing.JLabel();
        pwd_NewPassword = new javax.swing.JPasswordField();
        lbl_ForConfirmNewPassword = new javax.swing.JLabel();
        pwd_ConfirmNewPassword = new javax.swing.JPasswordField();
        jp_Save = new javax.swing.JPanel();
        btn_Save = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lbl_ForOldPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ForOldPassword.setForeground(java.awt.Color.yellow);
        lbl_ForOldPassword.setText("Old Password:");

        pwd_OldPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwd_OldPassword.setForeground(new java.awt.Color(51, 51, 51));
        pwd_OldPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        lbl_ForNewPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ForNewPassword.setForeground(java.awt.Color.yellow);
        lbl_ForNewPassword.setText("New Password:");

        pwd_NewPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwd_NewPassword.setForeground(new java.awt.Color(51, 51, 51));
        pwd_NewPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        lbl_ForConfirmNewPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ForConfirmNewPassword.setForeground(java.awt.Color.yellow);
        lbl_ForConfirmNewPassword.setText("Confirm New Password:");

        pwd_ConfirmNewPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwd_ConfirmNewPassword.setForeground(new java.awt.Color(51, 51, 51));
        pwd_ConfirmNewPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jp_Save.setBackground(new java.awt.Color(93, 53, 176));
        jp_Save.setBorder(new javax.swing.border.MatteBorder(null));
        jp_Save.setMaximumSize(new java.awt.Dimension(75, 28));
        jp_Save.setMinimumSize(new java.awt.Dimension(75, 28));

        btn_Save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Save.setForeground(new java.awt.Color(255, 255, 255));
        btn_Save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Save.setText("Save");
        btn_Save.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        btn_Save.setMaximumSize(new java.awt.Dimension(75, 25));
        btn_Save.setMinimumSize(new java.awt.Dimension(75, 25));
        btn_Save.setPreferredSize(new java.awt.Dimension(75, 25));
        btn_Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SaveMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jp_SaveLayout = new javax.swing.GroupLayout(jp_Save);
        jp_Save.setLayout(jp_SaveLayout);
        jp_SaveLayout.setHorizontalGroup(
            jp_SaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jp_SaveLayout.setVerticalGroup(
            jp_SaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jp_FormLayout = new javax.swing.GroupLayout(jp_Form);
        jp_Form.setLayout(jp_FormLayout);
        jp_FormLayout.setHorizontalGroup(
            jp_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_FormLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jp_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_ForNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addComponent(lbl_ForOldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl_ForConfirmNewPassword))
                .addGap(25, 25, 25)
                .addGroup(jp_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_FormLayout.createSequentialGroup()
                        .addComponent(jp_Save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(183, Short.MAX_VALUE))
                    .addGroup(jp_FormLayout.createSequentialGroup()
                        .addGroup(jp_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwd_ConfirmNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addGroup(jp_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pwd_OldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(pwd_NewPassword)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jp_FormLayout.setVerticalGroup(
            jp_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_FormLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jp_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ForOldPassword)
                    .addComponent(pwd_OldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ForNewPassword)
                    .addComponent(pwd_NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ForConfirmNewPassword)
                    .addComponent(pwd_ConfirmNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jp_Save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SaveMouseClicked
        // TODO add your handling code here:
        if (pwd_OldPassword.getPassword().length == 0 || pwd_NewPassword.getPassword().length == 0 || pwd_ConfirmNewPassword.getPassword().length == 0) {
            showMessage("please fill the required fields (old password, new password, confirm new password).");
        } else if (pwd_NewPassword.getPassword().length < 6) {
            showMessage("Password must contain at least 6 characters!");
        } else if (Arrays.equals(pwd_OldPassword.getPassword(), pwd_NewPassword.getPassword())) {
            showMessage("Your old and new password are the same!");
        } else if (!Arrays.equals(pwd_NewPassword.getPassword(), pwd_ConfirmNewPassword.getPassword())) {
            showMessage("Your password and confirmation password do not match!");
        } else {
            userController.changePassword();
        }
    }//GEN-LAST:event_btn_SaveMouseClicked

    private void btn_SaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SaveMouseEntered
        // TODO add your handling code here:
        jp_Save.setBackground(jp_Save.getBackground().brighter());
    }//GEN-LAST:event_btn_SaveMouseEntered

    private void btn_SaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SaveMouseExited
        // TODO add your handling code here:
        jp_Save.setBackground(new Color(93, 53, 176));
    }//GEN-LAST:event_btn_SaveMouseExited

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        clientMainView.setCheckMyChangePasswordView(false);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChangePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChangePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChangePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChangePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnabpwd_NewPassword      public void run() {
//                new ChangePasswordView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Save;
    private javax.swing.JPanel jp_Form;
    private javax.swing.JPanel jp_Save;
    private javax.swing.JLabel lbl_ForConfirmNewPassword;
    private javax.swing.JLabel lbl_ForNewPassword;
    private javax.swing.JLabel lbl_ForOldPassword;
    private javax.swing.JPasswordField pwd_ConfirmNewPassword;
    private javax.swing.JPasswordField pwd_NewPassword;
    private javax.swing.JPasswordField pwd_OldPassword;
    // End of variables declaration//GEN-END:variables
}
