/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.UIManager;
import model.User;

/**
 *
 * @author Valdez
 */
public class ParticipantRenderer extends javax.swing.JPanel implements ListCellRenderer<User> {
    
    private final String file_path = "file/icon/";

    /**
     * Creates new form UserRenderer
     */
    public ParticipantRenderer() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
        }
        initComponents();
    }
    
    public void displayStatus(User user) {
        try {
            String status_path = file_path;
            int temp = user.getStatus();
            switch (temp) {
                case 0:
                    status_path += "online-icon.png";
                    break;
                case 1:
                    status_path += "away-icon.png";
                    break;
                case 2:
                    status_path += "busy-icon.png";
                    break;
                case 3:
                    status_path += "invisible-icon.png";
                    break;
                case 4:
                    status_path += "offline-icon.png";
                    break;
            }
            BufferedImage status = ImageIO.read(new File(status_path));
            ImageIcon status_img = new ImageIcon(status);
            lbl_DisplayName.setIcon(status_img);
        } catch (IOException ex) {
        }
    }
    
    public void displayName(User user) {
        if (user.getDisplay_name().length() > 13) {
            lbl_DisplayName.setText(user.getDisplay_name().substring(0, 11) + "...");
        } else {
            lbl_DisplayName.setText(user.getDisplay_name());
        }
        this.setToolTipText(user.getDisplay_name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_DisplayName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(163, 73, 164));

        lbl_DisplayName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_DisplayName.setForeground(java.awt.Color.yellow);
        lbl_DisplayName.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_DisplayName, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_DisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Component getListCellRendererComponent(JList<? extends User> list, User value, int index, boolean isSelected, boolean cellHasFocus) {
        try {
            displayStatus(value);
            displayName(value);
            return this;
        } catch (Exception ex) {
            return null;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_DisplayName;
    // End of variables declaration//GEN-END:variables
}
